services:
  postgres:
    image: postgres:17
    container_name: logistics-postgres
    environment:
      POSTGRES_DB: logistics
      POSTGRES_USER: logistics
      POSTGRES_PASSWORD: logistics
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  kafka:
    image: apache/kafka:4.1.1
    container_name: logistics-kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: CONTROLLER://:9093,HOST://:9092,DOCKER://:29092
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:29092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /var/lib/kafka/data

volumes:
  postgres_data:
  kafka_data:
