services:
  postgres:
    image: postgres:17
    container_name: logistics-postgres
    environment:
      POSTGRES_DB: logistics
      POSTGRES_USER: logistics
      POSTGRES_PASSWORD: logistics
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  kafka:
    image: apache/kafka:4.1.1
    container_name: logistics-kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: CONTROLLER://:9093,HOST://:9092,DOCKER://:29092
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:29092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,HOST:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_LOG_DIRS: /var/lib/kafka/data
  order-service:
    image: logistics-order-service:latest
    build:
      context: ../../services/order-service
    container_name: logistics-order-service
    environment:
      DATABASE_URL: postgres://logistics:logistics@postgres:5432/logistics
      KAFKA_BROKER: kafka:29092
      KAFKA_TOPIC: shipment-events
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
  routing-service:
    image: logistics-routing-service:latest
    build:
      context: ../../services/routing-service
    container_name: logistics-routing-service
    environment:
      DATABASE_URL: postgres://logistics:logistics@postgres:5432/logistics
      KAFKA_BROKER: kafka:29092
      KAFKA_TOPIC: shipment-events
    depends_on:
      - postgres
      - kafka
  prediction-service:
    image: logistics-prediction-service:latest
    build:
      context: ../../services/prediction-service
    container_name: logistics-prediction-service
    environment:
      DATABASE_URL: postgresql://logistics:logistics@postgres:5432/logistics
      KAFKA_BROKER: kafka:29092
      KAFKA_TOPIC: shipment-events
      PYTHONUNBUFFERED: "1"
    depends_on:
      - postgres
      - kafka
  ministack:
    image: ministackorg/ministack:1.5.0
    container_name: logistics-ministack
    ports:
      - "4566:4566"
    environment:
      PERSIST_STATE: "1"
      STATE_DIR: /tmp/ministack-state
      DOCKER_NETWORK: docker_default
      LOG_LEVEL: INFO
    volumes:
      - ministack_state:/tmp/ministack-state
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  kafka_data:
  ministack_state:
